openapi: 3.0.1
tags:
- name: ping
  description: Ping
paths:
  /ping/call:
    get:
      tags:
      - ping
      summary: Restituisce l'utente per l'operatore
      operationId: call
      responses:
        "200":
          description: Risposta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Messaggio'
        "0":
          description: Errore sul sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /ping/current-date:
    get:
      tags:
      - ping
      summary: Restituisce la data corrente
      operationId: getCurrentDate
      responses:
        "200":
          description: Risposta
          content:
            application/json:
              schema:
                type: string
                format: date-time
        "0":
          description: Errore sul sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /ping/test-chiamata:
    get:
      tags:
      - ping
      summary: Test chiamata
      operationId: testChiamata
      responses:
        "200":
          description: Risposta
          content:
            application/json:
              schema:
                type: string
                format: date-time
        "0":
          description: Errore sul sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    ApiError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Messaggio:
      type: object
      properties:
        codSilapDMessaggio:
          type: string
        dsSilapDMessaggio:
          type: string
        dsTitolo:
          type: string
        flgAttivo:
          type: string
        idSilapDMessaggio:
          type: integer
          format: int64
        silapDTipoMessaggio:
          $ref: '#/components/schemas/TipoMessaggio'
    TipoMessaggio:
      type: object
      properties:
        dsSilapDTipoMessaggio:
          type: string
        idSilapDTipoMessaggio:
          type: string
