/*-
 * ========================LICENSE_START=================================
 * colmirbff
 * %%
 * Copyright (C) 2024 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2024 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.csi.silap.colmirbff.cxf.silpsvaa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2023-07-13T10:02:05.190+02:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "fault", targetNamespace = "urn:silpsvaa")
public class ServiziSilpException_Exception extends Exception {
    
    private it.csi.silap.colmirbff.cxf.silpsvaa.ServiziSilpException fault;

    public ServiziSilpException_Exception() {
        super();
    }
    
    public ServiziSilpException_Exception(String message) {
        super(message);
    }
    
    public ServiziSilpException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiziSilpException_Exception(String message, it.csi.silap.colmirbff.cxf.silpsvaa.ServiziSilpException fault) {
        super(message);
        this.fault = fault;
    }

    public ServiziSilpException_Exception(String message, it.csi.silap.colmirbff.cxf.silpsvaa.ServiziSilpException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public it.csi.silap.colmirbff.cxf.silpsvaa.ServiziSilpException getFaultInfo() {
        return this.fault;
    }
}
