/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Ccnl { 
    cod?: string;
    dataFine?: Date;
    dataInizio?: Date;
    descr?: string;
    dsSettore?: string;
    id?: string;
    numOre?: number;
}