/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Provincia } from './provincia';

export interface Comune { 
    dataFine?: Date;
    dataInizio?: Date;
    descr?: string;
    id?: string;
    silapDProvincia?: Provincia;
}