/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FormPrevisioniVersamentoEsoneri { 
    anno?: string;
    attachment?: Array<string>;
    email?: string;
}