/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Funzione { 
    dFine?: Date;
    dInizio?: Date;
    dsEstesa?: string;
    dsSilapDFunzione?: string;
    iconaSilapDFunzione?: string;
    idSilapDFunzione?: number;
    noteSilapDFunzione?: string;
}