/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PosizioneDebitoria { 
    cfDebitore?: string;
    codAvviso?: string;
    codIdPagamento?: string;
    codIur?: string;
    codIuv?: string;
    codTransazione?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    codVersamento?: string;
    dsCausale?: string;
    dsDebitore?: string;
    dsInfoAggiuntive?: string;
    dsNote?: string;
    dsPsp?: string;
    dsSoggettoVersante?: string;
    dtAggiorn?: Date;
    dtEsito?: Date;
    dtFineValidita?: Date;
    dtInizioValidita?: Date;
    dtInserim?: Date;
    dtInvioPromemoria?: Date;
    dtOperazione?: Date;
    dtScadenza?: Date;
    idEsoTPosizioneDebitoria?: number;
    importoAtteso?: number;
    importoPagato?: number;
    ntimestamp?: number;
    numRata?: number;
}