/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Provincia { 
    dataFine?: Date;
    dataInizio?: Date;
    descr?: string;
    dsSilapDProvincia?: string;
    id?: string;
}