/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Funzione } from './funzione';

export interface RuoloFunzione { 
    dataFine?: Date;
    dataInizio?: Date;
    funzione?: Funzione;
}