/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ruolo } from './ruolo';

export interface Utente { 
    codFisc?: string;
    cognome?: string;
    community?: string;
    ente?: string;
    livAuth?: number;
    nome?: string;
    ruoli?: Array<Ruolo>;
    ruolo?: string;
}