/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VersamentoCobLav } from './versamentoCobLav';

export interface VersamentoPvCob { 
    dCob?: Date;
    esoTVersamentoCobLavs?: Array<VersamentoCobLav>;
    idEsoTVersamentoPvCob?: number;
    numLavoratori?: number;
    numLavoratoriDisabili?: number;
}