/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';

export interface VersamentoSede { 
    codCap?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    comune?: Comune;
    dAggiorn?: Date;
    dInserim?: Date;
    dsDenominazioneSede?: string;
    dsIndirizzo?: string;
    idEsoTVersamentoSede?: number;
    idSilAziSede?: number;
    nTimestamp?: number;
}