/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VersamentoPvRicIn { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dRiconoscimentoInvalidita?: Date;
    dScadenza?: Date;
    idEsoTVersamentoPvRicIn?: number;
    nTimestamp?: number;
    numOreSettMed?: number;
}