/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VersamentoEsoneriRidotto { 
    annoProtocollo?: number;
    annoRiferimento?: number;
    codFiscale?: string;
    descStato?: string;
    dsDenominazioneAzienda?: string;
    dtEsito?: Date;
    dtStato?: Date;
    idEsoDVersamentoStato?: number;
    idEsoTVersamento?: number;
    importo?: number;
    importoPagato?: number;
    numProtocollo?: number;
    numRata?: number;
}