/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VersamentoPvGgExtraFestivi { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dGgFestivo?: Date;
    dInserim?: Date;
    idEsoTVersamentoPvGgExtraFestivi?: number;
    nTimestamp?: number;
}