/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VersamentoTipoConvenzione { 
    dFine?: Date;
    dInizio?: Date;
    dsEsoDVersamentoTipoConvenzione?: string;
    idEsoDVersamentoTipoConvenzione?: number;
    idSilL68TipoConvenzione?: string;
}