/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VersamentoPvEsonero { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dClassificazione?: Date;
    dConcessione?: Date;
    dDiniego?: Date;
    dInserim?: Date;
    dRichiesta?: Date;
    dScadenza?: Date;
    dsTipoComunicazione?: string;
    idEsoTVersamentoPvEsonero?: number;
    nTimestamp?: number;
    numClassificazione?: number;
    percConcessione?: number;
    percRichiesta?: number;
}