/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DVersamentoStato } from './dVersamentoStato';

export interface VersamentoStato { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dsNote?: string;
    dtStato?: Date;
    esoDVersamentoStato?: DVersamentoStato;
    flgCurrentRecord?: string;
    idEsoTVersamento?: number;
    idEsoTVersamentoStato?: number;
    nTimestamp?: number;
}