/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiMessage } from './apiMessage';
import { VersamentoPvPeriodo } from './versamentoPvPeriodo';

export interface VersamentoPvPeriodosResponse { 
    apiMessages?: Array<ApiMessage>;
    esitoPositivo?: boolean;
    periodi?: Array<VersamentoPvPeriodo>;
}