/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VersamentoCobLav { 
    codFiscale?: string;
    codiceComunicazioneReg?: string;
    dsCognome?: string;
    dsNome?: string;
    dsTipoComunicazione?: string;
    dsTipoContratto?: string;
    flgFulltime?: string;
    flgL68?: string;
    idEsoTVersamentoPvCobLav?: number;
    numOreSettMed?: number;
    siglaPv?: string;
}