/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VersamentoTipoConvenzione } from './versamentoTipoConvenzione';

export interface VersamentoPvConvenzione { 
    codUserAggiorn?: string;
    codUserInserim?: string;
    dAggiorn?: Date;
    dInserim?: Date;
    dScadenza?: Date;
    dStipula?: Date;
    esoDVersamentoTipoConvenzione?: VersamentoTipoConvenzione;
    idEsoTVersamentoPvConvenzione?: number;
    nTimestamp?: number;
    numPosizioniAperte?: number;
}