/*-
 * ========================LICENSE_START=================================
 * colmirbff
 * %%
 * Copyright (C) 2024 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2024 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.csi.silap.colmirbff.cxf.iupsv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2023-07-13T10:01:43.585+02:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "fault", targetNamespace = "urn:iupsv")
public class CSIException_Exception extends Exception {
    
    private it.csi.silap.colmirbff.cxf.iupsv.CSIException fault;

    public CSIException_Exception() {
        super();
    }
    
    public CSIException_Exception(String message) {
        super(message);
    }
    
    public CSIException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CSIException_Exception(String message, it.csi.silap.colmirbff.cxf.iupsv.CSIException fault) {
        super(message);
        this.fault = fault;
    }

    public CSIException_Exception(String message, it.csi.silap.colmirbff.cxf.iupsv.CSIException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public it.csi.silap.colmirbff.cxf.iupsv.CSIException getFaultInfo() {
        return this.fault;
    }
}
