/*-
 * ========================LICENSE_START=================================
 * colmirbff
 * %%
 * Copyright (C) 2024 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2024 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
package it.csi.silap.colmirbff.cxf.iupsv;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2023-07-13T10:01:43.636+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "IupsvSrvService", 
                  wsdlLocation = "./iup.wsdl",
                  targetNamespace = "urn:iupsv") 
public class IupsvSrvService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:iupsv", "IupsvSrvService");
    public final static QName Iupsv = new QName("urn:iupsv", "iupsv");
    static {
        URL url = IupsvSrvService.class.getResource("./iup.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(IupsvSrvService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "./iup.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public IupsvSrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IupsvSrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IupsvSrvService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IupsvSrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IupsvSrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IupsvSrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IupsvSrv
     */
    @WebEndpoint(name = "iupsv")
    public IupsvSrv getIupsv() {
        return super.getPort(Iupsv, IupsvSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IupsvSrv
     */
    @WebEndpoint(name = "iupsv")
    public IupsvSrv getIupsv(WebServiceFeature... features) {
        return super.getPort(Iupsv, IupsvSrv.class, features);
    }

}
