/*-
 * ========================LICENSE_START=================================
 * colmirbff
 * %%
 * Copyright (C) 2024 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2024 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */

package it.csi.silap.colmirbff.cxf.iupsv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2023-07-13T10:01:43.610+02:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "fault1", targetNamespace = "urn:iupsv")
public class SystemException_Exception extends Exception {
    
    private it.csi.silap.colmirbff.cxf.iupsv.SystemException fault1;

    public SystemException_Exception() {
        super();
    }
    
    public SystemException_Exception(String message) {
        super(message);
    }
    
    public SystemException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SystemException_Exception(String message, it.csi.silap.colmirbff.cxf.iupsv.SystemException fault1) {
        super(message);
        this.fault1 = fault1;
    }

    public SystemException_Exception(String message, it.csi.silap.colmirbff.cxf.iupsv.SystemException fault1, Throwable cause) {
        super(message, cause);
        this.fault1 = fault1;
    }

    public it.csi.silap.colmirbff.cxf.iupsv.SystemException getFaultInfo() {
        return this.fault1;
    }
}
